name: co2-vehicles-2025
channels:
  - conda-forge
  - defaults
dependencies:
  # Core (versions LTS 2025)
  - python=3.10.13 
  
  # Data Processing
  - pandas=2.2.3  
  - numpy=2.2.0
  - pyarrow=19.0.1
  - dask=2025.3.0
  
  # Machine Learning
  - scikit-learn=1.6.1
  
  # Visualization
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - plotly=6.0.1
  
  # Dashboarding
  - streamlit=1.44.0
  
  # Dev Tools
  - jupyterlab=4.3.6
  - pre-commit=4.2.0
  - black=25.1.0
  - flake8=7.2.0
  - pylint=3.3.6
  
  # Pip packages
  - pip=25.0.1
  - pip:
    - streamlit-aggrid==1.1.2
    - pyyaml==6.0.2